# Generated by Django 5.2.8 on 2025-11-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatar'),
        ('accounts', '0002_user_ismoderator_alter_user_avatar'),
    ]

    operations = [
    ]
